=== JetBrains/intellij-shared-indexes-tool-example/src/main/resources/commands-json-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "project": {
      "$ref": "#/definitions/not_empty_string"
    },
    "ijs": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ij"
      }
    },
    "options": {
      "type": "object",
      "properties": {
        "xmx": {
          "$ref": "#/definitions/not_empty_string"
        },
        "systemPropertiesToAdd": {
          "type": "object"
        },
        "systemPropertiesToRemove": {
          "$ref": "#/definitions/string_list"
        },
        "vmOptionsToAdd": {
          "$ref": "#/definitions/string_list"
        },
        "vmOptionPrefixesToRemove": {
          "$ref": "#/definitions/string_list"
        },
        "environmentVariablesToAdd": {
          "type": "object"
        },
        "environmentVariablesNameInfixToRemove": {
          "$ref": "#/definitions/string_list"
        }
      },
      "additionalProperties": false
    },
    "compression": {
      "enum": [
        "xz",
        "gzip",
        "plain"
      ]
    },
    "data-directory": {
      "$ref": "#/definitions/not_empty_string"
    },
    "base-url": {
      "$ref": "#/definitions/not_empty_string"
    },
    "upload-to-s3": {
      "type": "object",
      "properties": {
        "public-url": {
          "$ref": "#/definitions/not_empty_string"
        },
        "bucket": {
          "$ref": "#/definitions/not_empty_string"
        },
        "api-url": {
          "$ref": "#/definitions/not_empty_string"
        },
        "root-in-bucket": {
          "$ref": "#/definitions/not_empty_string"
        }
      },
      "additionalProperties": false
    },
    "timeout-minutes": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "project-id": {
      "$ref": "#/definitions/not_empty_string"
    }
  },
  "oneOf": [
    {
      "required": [
        "base-url"
      ]
    },
    {
      "required": [
        "upload-to-s3"
      ]
    }
  ],
  "required": [
    "project",
    "ijs",
    "project-id"
  ],
  "additionalProperties": false,
  "definitions": {
    "not_empty_string": {
      "type": "string",
      "minLength": 1
    },
    "ij": {
      "required": [
        "ij",
        "ij-type"
      ],
      "type": "object",
      "properties": {
        "ij": {
          "$ref": "#/definitions/not_empty_string"
        },
        "ij-type": {
          "enum": [
            "local",
            "url",
            "installer"
          ]
        }
      },
      "additionalProperties": false
    },
    "string_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/not_empty_string"
      }
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "upload-to-s3": {
            "not": {
              "type": "null"
            }
          }
        },
        "required": [
          "upload-to-s3"
        ]
      },
      "then": {
        "properties": {
          "upload-to-s3": {
            "required": [
              "public-url",
              "bucket",
              "api-url"
            ]
          }
        }
      }
    }
  ]
}

=== JetBrains/intellij-shared-indexes-tool-example/src/main/resources/validS3Json.json
{
  "ijs": [
    {
      "ij-type": "local",
      "ij": "C:\\Users\\user\\AppData\\Local\\JetBrains\\Toolbox\\apps\\PyCharm-P\\ch-0\\231.8109.197"
    }
  ],
  "project": "C:\\Users\\user\\workspace\\pet-project",
  "project-id": "pet-project",
  "data-directory": "ij-shared-indexes-tool-data",
  "timeout-minutes": 10,
  "options": {
    "xmx": "4096m",
    "environmentVariablesToAdd": {
      "MY_ENV_VAR": "VALUE"
    }
  },
  "compression": "plain",
  "upload-to-s3": {
    "public-url": "http://192.168.1.178:9000/shared-indexes/v2",
    "bucket": "shared-indexes",
    "api-url": "http://192.168.1.178:9000",
    "root-in-bucket": "v2"
  }
}

=== JetBrains/intellij-shared-indexes-tool-example/src/main/resources/validBaseJson.json
{
  "ijs": [
    {
      "ij-type": "url",
      "ij": "https://download.jetbrains.com/idea/ideaIU-2022.3.3.exe"
    }
  ],
  "project": "/home/user/workspace/java-design-patterns/",
  "project-id": "jdp",
  "data-directory": "ij-shared-indexes-tool-data",
  "timeout-minutes": 10,
  "options": {
    "xmx": "2048m",
    "environmentVariablesToAdd": {
      "MY_ENV_VAR": "VALUE"
    }
  },
  "compression": "plain",
  "base-url": "https://www.url.com"
}
